# Generated by Django 4.0.5 on 2022-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userGender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性別'),
        ),
    ]
