# Generated by Django 3.2.4 on 2021-06-11 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'yfcase_city',
            },
        ),
        migrations.CreateModel(
            name='Township',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yfcases.city')),
            ],
            options={
                'db_table': 'yfcase_township',
            },
        ),
        migrations.CreateModel(
            name='Yfcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yfcaseCaseNumber', models.CharField(max_length=100, verbose_name='案號(*)')),
                ('yfcaseCompany', models.CharField(blank=True, max_length=50, null=True, verbose_name='所屬公司')),
                ('yfcaseBigSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='段號')),
                ('yfcaseSmallSection', models.CharField(blank=True, max_length=10, null=True, verbose_name='小段')),
                ('yfcaseVillage', models.CharField(blank=True, max_length=100, null=True, verbose_name='村里')),
                ('yfcaseNeighbor', models.CharField(blank=True, max_length=100, null=True, verbose_name='鄰')),
                ('yfcaseStreet', models.CharField(blank=True, max_length=100, null=True, verbose_name='街路')),
                ('yfcaseSection', models.CharField(blank=True, max_length=100, null=True, verbose_name='段')),
                ('yfcaseLane', models.CharField(blank=True, max_length=100, null=True, verbose_name='巷')),
                ('yfcaseAlley', models.CharField(blank=True, max_length=100, null=True, verbose_name='弄')),
                ('yfcaseNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='號')),
                ('yfcaseFloor', models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(含之幾)')),
                ('yfcaseDebtor', models.CharField(blank=True, max_length=10, null=True, verbose_name='債務人')),
                ('yfcaseCreditor', models.CharField(blank=True, max_length=10, null=True, verbose_name='債權人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='區域負責人')),
                ('yfcaseCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yfcases.city', verbose_name='縣市')),
                ('yfcaseTownship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yfcases.township', verbose_name='鄉鎮區里')),
            ],
            options={
                'db_table': 'yfcase_yfcase',
            },
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='地號')),
                ('landUrl', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('landArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='地坪(平方公尺)')),
                ('landHoldingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='個人持分')),
                ('landHoldingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='所有持分')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='yfcases.yfcase')),
            ],
        ),
    ]
