# Generated by Django 3.2.4 on 2021-06-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildNumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='建號')),
                ('buildUrl', models.URLField(blank=True, null=True, verbose_name='謄本')),
                ('buildArea', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='建坪(平方公尺)')),
                ('buildHoldingPointPersonal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='個人持分')),
                ('buildHoldingPointAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='所有持分')),
                ('buildTypeUse', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物型')),
                ('buildUsePartition', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用分區')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='yfcases.yfcase')),
            ],
        ),
    ]
