# Generated by Django 3.1.3 on 2021-09-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseNumber',
            field=models.CharField(max_length=100, null=True, verbose_name='號'),
        ),
    ]
