# Generated by Django 3.2.4 on 2021-06-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0002_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auctionDateFirst', models.CharField(blank=True, max_length=100, null=True, verbose_name='拍賣日(第一拍)')),
                ('auctionDateSecond', models.CharField(blank=True, max_length=100, null=True, verbose_name='拍賣日(第二拍)')),
                ('auctionDateThird', models.CharField(blank=True, max_length=100, null=True, verbose_name='拍賣日(第三拍)')),
                ('auctionDateFourth', models.CharField(blank=True, max_length=100, null=True, verbose_name='拍賣日(第四拍)')),
                ('auctionFloorPriceFirst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='底價(第一拍)')),
                ('auctionFloorPriceSecond', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='底價(第二拍)')),
                ('auctionFloorPriceThird', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='底價(第三拍)')),
                ('auctionFloorPriceFourth', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='底價(第四拍)')),
                ('auctionClickFirst', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='點閱(第一拍)')),
                ('auctionClickSecond', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='點閱(第二拍)')),
                ('auctionClickThird', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='點閱(第三拍)')),
                ('auctionClickFourth', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='點閱(第四拍)')),
                ('auctionMonitorFirst', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='監控(第一拍)')),
                ('auctionMonitorSecond', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='監控(第二拍)')),
                ('auctionMonitorThird', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='監控(第三拍)')),
                ('auctionMonitorFourth', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='監控(第四拍)')),
                ('auctionMarginFirst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='保証金(第一拍)')),
                ('auctionMarginSecond', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='保証金(第二拍)')),
                ('auctionMarginThird', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='保証金(第三拍)')),
                ('auctionMarginFourth', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='保証金(第四拍)')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='yfcases.yfcase')),
            ],
        ),
    ]
