# Generated by Django 3.2.4 on 2021-06-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0003_yfcase_yfcasecitywithtownship'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCaseStatus',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='案件狀態'),
        ),
    ]
