# Generated by Django 3.2.4 on 2021-06-14 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0003_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyFirstDay', models.CharField(blank=True, max_length=100, null=True, verbose_name='初勘日')),
                ('surveySecondDay', models.CharField(blank=True, max_length=100, null=True, verbose_name='會勘日')),
                ('surveyForeclosureAnnouncementLink', models.URLField(blank=True, null=True, verbose_name='法拍公告(證物三)')),
                ('survey988Link', models.URLField(blank=True, null=True, verbose_name='998連結')),
                ('surveyObjectPhotoLink', models.URLField(blank=True, null=True, verbose_name='物件照片(證物四)')),
                ('surveyNetMarketPriceLink', models.URLField(blank=True, null=True)),
                ('surveyForeclosureRecordLink', models.URLField(blank=True, null=True, verbose_name='法拍記錄(證物七)')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='yfcases.yfcase')),
            ],
        ),
    ]
