# Generated by Django 3.1.3 on 2021-10-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0003_auto_20210927_0846'),
        ('yfcases', '0004_alter_build_buildnumber'),
    ]

    operations = [
    ]
