# Generated by Django 3.2.4 on 2021-06-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0006_finaldecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseCreditorMobilePhone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='債權人電話'),
        ),
    ]
