# Generated by Django 3.2.4 on 2021-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0007_yfcase_yfcasecreditormobilephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='buildHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分'),
        ),
        migrations.AlterField(
            model_name='build',
            name='buildHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landHoldingPointAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='所有持分'),
        ),
        migrations.AlterField(
            model_name='land',
            name='landHoldingPointPersonal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='個人持分'),
        ),
    ]
