# Generated by Django 3.2.4 on 2021-06-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0008_auto_20210615_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveyObjectViewLink',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='標的物(現場勘查)'),
        ),
    ]
