# Generated by Django 3.2.4 on 2021-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0008_auto_20210623_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintComplaintDate',
            field=models.DateField(blank=True, null=True, verbose_name='起訴狀填寫日期'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintExhibit1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='證物1'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintExhibit2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='證物2'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintExhibit3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='證物3'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintExhibit4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='證物4'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintLandDepth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='土地深度'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintLandWidth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='土地面寬'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintLitigationAgent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='訴訟代理人'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintPresentValueOfHouseTax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='房屋課稅現值'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintPresentValueOfLandAnnouncement',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地公告現值'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintRefereeFee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='裁判費'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseComplaintUnsuccessfulDate',
            field=models.DateField(blank=True, null=True, verbose_name='分割未果日期'),
        ),
    ]
