# Generated by Django 3.2.4 on 2021-06-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0009_auto_20210623_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOwnerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coOwnerName', models.CharField(blank=True, max_length=10, null=True, verbose_name='姓名')),
                ('coOwnerAddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('coOwnerLandHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地個人持分')),
                ('coOwnerLandHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地所有持分')),
                ('coOwnerBuildHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物個人持分')),
                ('coOwnerBuildHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物所有持分')),
                ('yfcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coownerinfos', to='yfcases.yfcase')),
            ],
        ),
    ]
