# Generated by Django 3.2.4 on 2021-06-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0009_survey_surveyobjectviewlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionDeterminationFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionDeterminationFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionDeterminationGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionDeterminationSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionDeterminationThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終判定(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadDateFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人簽核日期(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadDateFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人簽核日期(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadDateGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人簽核日期(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadDateSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人簽核日期(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadDateThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人簽核日期(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRemarkFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='備註(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRemarkFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='備註(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRemarkGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='備註(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRemarkSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='備註(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRemarkThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='備註(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionStopBuyDate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='一賣止日'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueAFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員A(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueAFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員A(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueAGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員A(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueASecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員A(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueAThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員A(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueBFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員B(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueBFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員B(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueBGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員B(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueBSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員B(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueBThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署人員B(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateAFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期A(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateAFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期A(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateAGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期A(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateASecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期A(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateAThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期A(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateBFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期B(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateBFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期B(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateBGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期B(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateBSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期B(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueDateBThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署日期B(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidAuctionFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標拍別(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidAuctionFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標拍別(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidAuctionSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標拍別(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidAuctionThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標拍別(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidMoneyFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標金額(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidMoneyFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標金額(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidMoneySecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標金額(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultBidMoneyThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='搶標金額(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultNoOneBuyFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='無人優購(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultNoOneBuyFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='無人優購(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultNoOneBuySecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='無人優購(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultNoOneBuyThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='無人優購(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultObjectNumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='標的編號'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultOtherBuyFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='遭優購(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultOtherBuyFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='遭優購(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultOtherBuySecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='遭優購(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultOtherBuyThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='遭優購(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWaitBuyFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等待優購(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWaitBuyFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等待優購(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWaitBuySecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等待優購(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWaitBuyThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等待優購(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWithdrawFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='撤回(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWithdrawFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='撤回(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWithdrawSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='撤回(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='resultWithdrawThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='撤回(三拍)'),
        ),
    ]
