# Generated by Django 3.1.3 on 2021-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0009_auto_20211015_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='bidMoney',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='搶標金額'),
        ),
    ]
