# Generated by Django 3.2.4 on 2021-06-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0010_auto_20210616_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finaldecision',
            name='finalDecisionStopBuyDate',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidAuctionFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidAuctionFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidAuctionSecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidAuctionThird',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidMoneyFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidMoneyFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidMoneySecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultBidMoneyThird',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultNoOneBuyFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultNoOneBuyFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultNoOneBuySecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultNoOneBuyThird',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultObjectNumber',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultOtherBuyFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultOtherBuyFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultOtherBuySecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultOtherBuyThird',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWaitBuyFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWaitBuyFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWaitBuySecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWaitBuyThird',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWithdrawFirst',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWithdrawFourth',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWithdrawSecond',
        ),
        migrations.RemoveField(
            model_name='finaldecision',
            name='resultWithdrawThird',
        ),
    ]
