# Generated by Django 3.2.4 on 2021-06-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0010_coownerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseLetterAgent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存證信函代理人'),
        ),
    ]
