# Generated by Django 3.2.4 on 2021-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0011_auto_20211104_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseSubFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓(之)'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseSubNumber',
            field=models.CharField(max_length=100, null=True, verbose_name='號(之)'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseFloor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='樓'),
        ),
    ]
