# Generated by Django 3.2.4 on 2021-06-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0011_auto_20210616_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadWorkAreaFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人轄區(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadWorkAreaFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人轄區(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadWorkAreaGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人轄區(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadWorkAreaSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人轄區(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionRegionalHeadWorkAreaThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='區域負責人轄區(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaAFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區A(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaAFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區A(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaAGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區A(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaASecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區A(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaAThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區A(三拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaBFirst',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區B(一拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaBFourth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區B(四拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaBGiveUp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區B(放棄)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaBSecond',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區B(二拍)'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionSubSigntrueWorkAreaBThird',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='副署轄區B(三拍)'),
        ),
    ]
