# Generated by Django 3.2.4 on 2021-06-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0011_yfcase_yfcaseletteragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='landRemark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
    ]
