# Generated by Django 4.2.2 on 2023-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0011_auto_20211104_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='surveyMoneytViewLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='流水帳'),
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyPagesViewLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='收發文薄'),
        ),
    ]
