# Generated by Django 3.2.4 on 2021-12-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_auto_20211230_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseSubNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='號(之)'),
        ),
    ]
