# Generated by Django 4.2.2 on 2023-06-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_survey_surveymoneytviewlink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemark',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='備註'),
        ),
    ]
