# Generated by Django 3.2.4 on 2021-06-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_auto_20210616_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemarkFirst',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註(一拍)'),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemarkFourth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註(四拍)'),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemarkGiveUp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註(放棄)'),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemarkSecond',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註(二拍)'),
        ),
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemarkThird',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註(三拍)'),
        ),
    ]
