# Generated by Django 3.2.4 on 2021-06-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0012_land_landremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='buildAncillaryBuildingArea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='附屬建物面積'),
        ),
        migrations.AddField(
            model_name='build',
            name='buildAncillaryBuildingUseBy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='附屬建物用途'),
        ),
        migrations.AddField(
            model_name='build',
            name='buildRemark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='備註'),
        ),
    ]
