# Generated by Django 4.2.2 on 2023-06-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0013_alter_finaldecision_finaldecisionremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionCaseCountFirst',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='成交件數(第一拍)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionCaseCountFourth',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='成交件數(第四拍)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionCaseCountSecond',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='成交件數(第二拍)'),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionCaseCountThird',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=4, null=True, verbose_name='成交件數(第三拍)'),
        ),
    ]
