# Generated by Django 3.2.4 on 2021-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0013_auto_20210629_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildSubBuildArea',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='增建坪數(坪)'),
        ),
    ]
