# Generated by Django 3.2.7 on 2022-01-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0013_alter_yfcase_yfcasesubnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='拍賣最後更新時間'),
        ),
        migrations.AddField(
            model_name='build',
            name='buildUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='建號最後更新時間'),
        ),
        migrations.AddField(
            model_name='finaldecision',
            name='finalDecisionUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='最終判定最後更新時間'),
        ),
        migrations.AddField(
            model_name='objectbuild',
            name='objectBuildingUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='參考物件最後更新時間'),
        ),
        migrations.AddField(
            model_name='result',
            name='resultUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='結果最後更新時間'),
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyUpdated',
            field=models.DateTimeField(auto_now=True, verbose_name='勘查最後更新時間'),
        ),
    ]
