# Generated by Django 4.0.5 on 2022-06-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0014_auto_20220102_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finaldecision',
            name='finalDecisionRemark',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='備註'),
        ),
    ]
