# Generated by Django 3.2.4 on 2021-07-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0014_objectbuild_objectbuildsubbuildarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='coownerinfo',
            name='coOwnerLifeOrDie',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='存/殁'),
        ),
    ]
