# Generated by Django 3.2.13 on 2022-06-19 15:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0015_alter_finaldecision_finaldecisionremark'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='build',
            managers=[
                ('s_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
