# Generated by Django 3.2.4 on 2021-07-03 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0015_coownerinfo_coownerlifeordie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOwnerHeir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coOwnerHeirName', models.CharField(blank=True, max_length=10, null=True, verbose_name='姓名')),
                ('coOwnerHeirAddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('coOwnerHeirLandHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地個人持分')),
                ('coOwnerHeirLandHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地所有持分')),
                ('coOwnerHeirBuildHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物個人持分')),
                ('coOwnerHeirBuildHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物所有持分')),
                ('coOwnerHeirLifeOrDie', models.CharField(blank=True, max_length=4, null=True, verbose_name='存/殁')),
                ('coowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coownerheirs', to='yfcases.coownerinfo')),
            ],
        ),
    ]
