# Generated by Django 3.2.13 on 2022-06-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0016_alter_build_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='build',
            managers=[
            ],
        ),
    ]
