# Generated by Django 3.2.4 on 2021-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0016_result_objectnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='noOneBuy',
            field=models.BooleanField(default=False, verbose_name='無人優購'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='otherBuy',
            field=models.BooleanField(default=1, verbose_name='遭優購'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='waitBuy',
            field=models.BooleanField(default=1, verbose_name='等待優購'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='withdraw',
            field=models.BooleanField(default=1, verbose_name='撤回'),
            preserve_default=False,
        ),
    ]
