# Generated by Django 3.2.4 on 2021-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0017_auto_20210617_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='noOneBuy',
        ),
        migrations.RemoveField(
            model_name='result',
            name='otherBuy',
        ),
        migrations.RemoveField(
            model_name='result',
            name='waitBuy',
        ),
        migrations.RemoveField(
            model_name='result',
            name='withdraw',
        ),
        migrations.AddField(
            model_name='result',
            name='actionResult',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='執行結果'),
        ),
    ]
