# Generated by Django 3.2.4 on 2021-07-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0017_coownerheir_coownerserial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coownerheir',
            old_name='coOwnerSerial',
            new_name='coOwnerHeirSerial',
        ),
    ]
