# Generated by Django 3.2.4 on 2021-07-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0018_rename_coownerserial_coownerheir_coownerheirserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coownerheir',
            name='coOwnerHeirSerial',
        ),
        migrations.AddField(
            model_name='coownerheir',
            name='coOwnerHeirIdentityCard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身分証號'),
        ),
        migrations.AddField(
            model_name='coownerinfo',
            name='coOwnerIdentityCard',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身分証號'),
        ),
    ]
