# Generated by Django 3.2.4 on 2021-07-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0019_auto_20210704_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='coownerheir',
            name='coOwnerHeirType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='種類'),
        ),
    ]
