# Generated by Django 3.2.4 on 2021-07-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0020_coownerheir_coownerheirtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coownerheir',
            name='coOwnerHeirType',
        ),
    ]
