# Generated by Django 3.2.4 on 2021-07-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0021_remove_coownerheir_coownerheirtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOwnerLitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coOwnerLitigationName', models.CharField(blank=True, max_length=10, null=True, verbose_name='姓名')),
                ('coOwnerLitigationIdentityCard', models.CharField(blank=True, max_length=50, null=True, verbose_name='身分証號')),
                ('coOwnerLitigationAddress', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('coOwnerLitigationLandHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地個人持分')),
                ('coOwnerLitigationLandHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='土地所有持分')),
                ('coOwnerLitigationBuildHPPersonnal', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物個人持分')),
                ('coOwnerLitigationBuildHPAll', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='建物所有持分')),
                ('coOwnerLitigationLifeOrDie', models.CharField(blank=True, max_length=4, null=True, verbose_name='存/殁')),
                ('coownerheir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coownerheirs', to='yfcases.coownerheir')),
            ],
        ),
    ]
