# Generated by Django 3.2.4 on 2021-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0025_auto_20210709_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseDeedtaxSendAddress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='寄送地址'),
        ),
    ]
