# Generated by Django 3.2.4 on 2021-07-10 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0026_yfcase_yfcasedeedtaxsendaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yfcase',
            name='yfcaseDeedtaxSendAddress',
        ),
    ]
