# Generated by Django 3.2.4 on 2021-08-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0027_remove_yfcase_yfcasedeedtaxsendaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseCreditor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='債權人'),
        ),
        migrations.AlterField(
            model_name='yfcase',
            name='yfcaseDebtor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='債務人'),
        ),
    ]
