# Generated by Django 3.2.4 on 2021-08-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0028_auto_20210807_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='surveyObjectViewLink',
            field=models.URLField(blank=True, null=True, verbose_name='標的物(現場勘查)'),
        ),
    ]
