# Generated by Django 3.2.4 on 2021-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0029_alter_survey_surveyobjectviewlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='surveyForeclosureAnnouncementLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='法拍公告(證物三)'),
        ),
    ]
