# Generated by Django 3.2.4 on 2021-08-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0030_alter_survey_surveyforeclosureannouncementlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey988Link',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='998連結'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyForeclosureRecordLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='法拍記錄(證物七)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyNetMarketPriceLink',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyObjectPhotoLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='物件照片(證物四)'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyObjectViewLink',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='標的物(現場勘查)'),
        ),
    ]
