# Generated by Django 3.2.4 on 2021-08-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0031_auto_20210807_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectbuild',
            name='objectBuildUrl',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='附件'),
        ),
    ]
