# Generated by Django 3.2.4 on 2021-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0033_alter_result_stopbuydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseAllCoOwnerLandHPAll',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='所有土地持分'),
        ),
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseAllCoOwnerLandHPPersonnal',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8, null=True, verbose_name='所有共有人應土地持分'),
        ),
    ]
