# Generated by Django 3.2.4 on 2021-08-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0034_auto_20210809_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='yfcase',
            name='yfcaseLetterSender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='存證信函寄件人'),
        ),
    ]
