# Generated by Django 3.2.4 on 2021-08-11 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yfcases', '0035_yfcase_yfcaselettersender'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldecision',
            name='regionalHeadAddDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='區域負責人存檔日期'),
        ),
    ]
